FROM golang:1.23.1-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o notification-service cmd/notificationservice/main.go

FROM alpine

WORKDIR /root/

COPY --from=builder /app/notification-service .

COPY --from=builder /app/templates ./templates

EXPOSE 50051
CMD ["./notification-service"]