apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: negat1ff/product-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 50051
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: DATABASE_URL
          value: "mongodb://user:password@192.168.31.56:27017"
        - name: MESSAGE_BROKER_URL
          value: amqp://rabbitmq_user:rabbitmq_password@192.168.31.56:5672
        - name: MESSAGE_BROKER_EXCHANGE
          value: productExchange
        - name: CACHE_URL
          value: redis://192.168.31.56:6379
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8080
  - name: grpc
    protocol: TCP
    port: 50052
    targetPort: 50051