apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: negat1ff/product-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 50051
        env:
        - name: LOG_LEVEL
          value: INFO
        - name: DATABASE_URL
          value: jdbc:postgresql://postgres:5432/productdb
        - name: MESSAGE_BROKER_URL
          value: product-service-rabbitmq
        - name: MESSAGE_BROKER_EXCHANGE
          value: product-service-exchange
        - name: CACHE_URL
          value: product-service-redis
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
  - protocol: TCP
    port: 50052
    targetPort: 50051