FROM golang:1.23.1-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o product-service cmd/productservice/main.go

FROM alpine

WORKDIR /root/

COPY --from=builder /app/product-service .

EXPOSE 8080
EXPOSE 50051
CMD ["./product-service"]