apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
      - name: shopping-cart-service
        image: negat1ff/shopping-cart-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: jwt-secret-key
        - name: DATABASE_URL
          value: "postgresql://user:password@192.168.31.56:5432/cart_db"
        - name: PRICE_SERVICE
          value: "product-service:50052"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  selector:
    app: shopping-cart-service
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8080