FROM golang:1.23.1-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o shopping-cart-service cmd/shoppingcartservice/main.go

FROM alpine

WORKDIR /root/

COPY --from=builder /app/shopping-cart-service .

EXPOSE 8080
CMD ["./shopping-cart-service"]