apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: negat1ff/payment-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: stripe-webhook-secret-key
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: stripe-secret-key
        - name: DATABASE_URL
          value: postgresql://user:password@192.168.31.56:5432/payment_db
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080