FROM golang:1.23.1-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o user-service cmd/userservice/main.go

FROM alpine

WORKDIR /root/

COPY --from=builder /app/user-service .

EXPOSE 8080
CMD ["./user-service"]