apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: negat1ff/search-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ELASTICSEARCH_URL
          value: http://192.168.31.56:9200
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: elastic-user
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: elastic-password
        - name: RABBITMQ_URL
          value: amqp://rabbitmq_user:rabbitmq_password@192.168.31.56:5672
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8080