name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Find Dockerfiles and build images
        run: |
          for dir in $(find . -name Dockerfile -exec dirname {} \;); do
            image_name=$(basename $dir)
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$image_name:latest $dir
            docker push ${{ secrets.DOCKER_USERNAME }}/$image_name:latest
          done